### ISSUE TITLE
The PEAR repository has been removed from Composer 2.0

### ISSUE THREAD

**Issue by SLAY3RYTB** [detrout/irony#2]
Hey, im testing install irony for roundcube but im have an probleme.

If im follow your tutorial im going on my CMD and execute command [curl -s http://getcomposer.org/installer | php], there update the files composer.phar in version 2.0.1 but pear repository have been removed on this version, if im take a composer.phar in version 1.10.16 on https://getcomposer.org/download/ and im execute commande [php composer.phar install] im get an error.

For the second problem, how to import Roundcube Framework, Kolab plugins and Chwala and how get the file beacause your tutorial is not really well explained

3.1. Either copy or symlink the Roundcube framework package into lib/Roundcube 3.2. Either copy or symlink the roundcubemail-plugins-kolab into lib/plugins 3.3. Either copy or symlink the Chwala lib/ directory into lib/FileAPI

And for the last problem how to get main.inc.php and db.inc.php and how to create an smylink.

Thanks for your help, im really need that for my work.

Sorry for my english, im french people.

https://gyazo.com/e186eb8b826294b2b4c887e20208ca79
https://gyazo.com/c1ce50f857ce28675ec06d479f540830

**Comment by detrout** [comment]
This is just a personal clone of the upstream repository that I think is at https://git.kolab.org/project/profile/7/ I'm not actually doing anything with it, if you want to contribute you should probably talk to the real maintainers
